[Feat] Search view/UI
DeveloperAcademy-POSTECH/MacC-Team-HappyAnding pull request #241
Opened 2022-11-12 01:35 UTC by otoolz

## 관련 이슈
- closes #235 

## 구현/변경 사항
- 검색 관련 화면 UI
    - ExploreShortcutView 탐색버튼
    - 서치뷰
    - 서치 결과 뷰 ( 결과 있을 때, 없을 때) 

## 스크린샷

|proposeView|SearchView|ExploreShortcutView 탐색버튼|
|:---:|:---:|:---:|
|![IMG_4335](https://user-images.githubusercontent.com/91725382/201450378-779c218a-c31e-4bb8-87cc-46e3f749b556.PNG)|![IMG_4334](https://user-images.githubusercontent.com/91725382/201450385-fccfd4f3-ce3f-44f5-bc18-f14b54b5fd22.PNG)|![IMG_4333](https://user-images.githubusercontent.com/91725382/201450393-30076854-88bc-48f5-9c6f-ca0202bdc53b.PNG)|

2022-11-12 08:55 UTC, JMM00 approved these changes
확인했습니다~! 검색 기능 추가해야할 부분을 명시해주셔서 제가 편하게 작업할 수 있었습니다~! 최고최고!!

2022-11-12 08:55 UTC, JMM00 commented on HappyAnding/HappyAnding/Views/SearchView.swift
> +                    // TODO: 선택된 텍스트 검색하는 기능
제가 기능 구현해서 함께 pr올렸습니다~!

2022-11-12 08:55 UTC, JMM00 commented on HappyAnding/HappyAnding/Views/SearchView.swift
> +    let keywords: [String] = ["단축어", "갓생", "포항꿀주먹"]
추천 검색어를 쉽게 변경하기 위해서 서버에서 추천 검색어를 저장하도록 추가로 구현해볼까요?

2022-11-12 08:55 UTC, JMM00 commented on HappyAnding/HappyAnding/Views/SearchView.swift
> +
```suggestion
                //TODO: 버튼 클릭 시 단축어 제안하는 페이지 연결
```

추후 기능이 구현되어야하는 부분이라서 주석 추가해두면 좋을 것 같습니다!

2022-11-12 11:17 UTC, otoolz commented on HappyAnding/HappyAnding/Views/SearchView.swift
> +    let keywords: [String] = ["단축어", "갓생", "포항꿀주먹"]
와우 너무 좋겠는걸요?

2022-11-12 11:17 UTC, otoolz commented on HappyAnding/HappyAnding/Views/SearchView.swift
> +                    // TODO: 선택된 텍스트 검색하는 기능
긋긋긋👍

2022-11-12 11:18 UTC, otoolz commented on HappyAnding/HappyAnding/Views/SearchView.swift
> +
넹 추가하겠슴다!

2022-11-12 16:10 UTC, JIWON1923 approved these changes
LGTM!
기존 커스텀했던 x (지우기) 버튼은 없어도 될 것 같아요!

2022-11-13 06:47 UTC, JMM00 commented
홍기 테스트할 때는 google plist 변경해서 작업해주세요!

2022-11-13 13:58 UTC, HanGyeongjun requested changes
수고하셨습니다! 패딩 30으로 준 부분 로미와 확인 후 머지하면 될 것 같습니다 👍🏻

2022-11-13 13:58 UTC, HanGyeongjun commented on HappyAnding/HappyAnding/Views/SearchView.swift
> +
```suggestion
```

2022-11-13 13:58 UTC, HanGyeongjun commented on HappyAnding/HappyAnding/Views/SearchView.swift
> +                    .padding(.horizontal, 30)
4배수가 아니라서 한 번 디자이너와 확인해보면 좋을 것 같습니다
@mxnxxii

2022-11-13 13:58 UTC, HanGyeongjun commented on HappyAnding/HappyAnding/Views/SearchView.swift
> +                            .padding(10)
```suggestion
                            .padding(.horizontal, 12)
                            .padding(.vertical, 8)
```

2022-11-13 13:58 UTC, HanGyeongjun commented on HappyAnding/HappyAnding/Views/SearchView.swift
> +                .padding(.leading, 16)
첫번째 셀 이후의 사이 간격은 padding이 12라서 화면 좌우 영역의 패딩과는 따로 적용되야 할 것 같습니다!
```suggestion
                .padding(.leading, 12)
```

2022-11-13 14:09 UTC, HanGyeongjun commented
여기 border 있는 뷰에서도 라인 일부가 잘리는 현상이 있네요. 제가 작성한 WriteCurationSetView에서도 동일한 문제가 발생했었는데, 이슈 작성 후 머지되면 제 뷰와 함께 수정작업해보겠습니다!
아마도 뷰 내부에 border가 그려지는 게 아니라 경계선을 중심으로 그려져서 외부에 그려진 border가 잘리는게 원인 같은데 확인해보겠습니다.

2022-11-13 16:53 UTC, mxnxxii approved these changes

2022-11-13 16:53 UTC, mxnxxii commented on HappyAnding/HappyAnding/Views/SearchView.swift
> +                    .padding(.horizontal, 30)
Figma상, 4배수보다 마진이 우선시되어서 4배수 적용이 되지 않은것으로 확인됩니다 :)
자세한 내용은 직접 만나서 확인 후 수정하는것으로 진행하도록 해볼게요 !!

2022-11-13 16:54 UTC, mxnxxii reviewed
서치 결과검색 부분 background가 white로 구현되어있는 것 같은데 확인 부탁드릴게요 :)

2022-11-14 07:55 UTC, otoolz commented on HappyAnding/HappyAnding/Views/SearchView.swift
> +                    .padding(.horizontal, 30)
넹 28로 적용하겠습니다

2022-11-14 08:13 UTC, otoolz commented
수정 요청사항들 확인하고 반영했습니다~
@HanGyeongjun 확인하시면 바로 머지 하겠습니다~~

2022-11-14 08:17 UTC, HanGyeongjun approved these changes

2022-11-14 08:21 UTC, merged