[Feat] curation deeplink 기능 추가
DeveloperAcademy-POSTECH/MacC-Team-HappyAnding pull request #300
Opened 2022-11-24 07:27 UTC by otoolz

## 관련 이슈
- closes #299 

## 구현/변경 사항
- 유저 큐레이션 딥링크 기능 추가

## 유저 큐레이션 카톡으로 딥링크 귱유

https://user-images.githubusercontent.com/91725382/203719423-b686b1b9-9ee6-49d4-ac88-59a5896aa4dd.MP4

## 공유받은 유저 큐레이션 딥링크 실행

https://user-images.githubusercontent.com/91725382/203719387-69c71d8d-27d2-4652-81d4-ff5de1951e45.MP4

2022-11-24 13:35 UTC, HanGyeongjun approved these changes
큐레이션 공유도 깔끔하게 잘 되는군요! 수고하셨습니다

2022-11-24 13:35 UTC, HanGyeongjun commented on HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
> +            Text("\(shortcutsZipViewModel.userInfo?.nickname ?? "")\(data.type.rawValue)이 없습니다.")
메시지에 닉네임이 추가되었군요!

2022-11-25 08:09 UTC, jim4020key reviewed
큐레이션 삭제기능이 사라졌어요 !!!! 🚨

2022-11-25 11:50 UTC, JIWON1923 commented
<img src = "https://user-images.githubusercontent.com/68676844/203979587-5ef53f80-87e5-4141-9b46-a2dd3ccacf6e.jpeg" width=250> 
네비게이션 타이틀 수정 부탁드립니다!

2022-11-25 11:58 UTC, JIWON1923 reviewed
LGTM! iOS 16.0 실기기 테스트 완료했습니다!

그린이 말씀해주신 부분만 수정해서 머지하면 될 것 같아요~! (따로 approve 하지 않겠습니다!!)
지금 앱이 없을 때, 링크를 클릭해도 반응이 없네요!! (이 부분은 따로 이슈 끊어 놓겠습니다! 팀원들과 이야기해보고 sprin4나 5에서 해결하면 좋을 것 같아요!)

2022-11-25 19:10 UTC, JMM00 reviewed
확인했습니다! 그린이 말한 메뉴버튼만 수정해주시면 될 것 같습니다~!

2022-11-25 19:10 UTC, JMM00 commented on HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
> +            Text("\(titleString)\(data.type.rawValue)이 없습니다.")
👍 타입에 따라서 들어가고 안들어가고를 구분해주셨네요 좋아요

2022-11-26 07:52 UTC, JMM00 reviewed
큐레이션 편집도 넣어주세요..!

2022-11-26 07:52 UTC, JMM00 commented on HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
> +    private var myCurationMenu: some View {
👍👍👍

2022-11-26 08:04 UTC, mxnxxii approved these changes

2022-11-26 08:05 UTC, otoolz commented
새롭게 수정한거
- 큐레이션 삭제 버튼 복구
- 메뉴에 공유만 있는 경우(큐레이션) 메뉴 대신 공유 버튼으로 변경
- 메뉴에 공유만 있는 경우(단축어) 메뉴 대신 공유 버튼으로 변경
- xx님을 위한 모음집 들어갔을 때 네비타이틀 텍스트 안바뀌던거 수정

## 스크린샷
|내가 작성한 큐레이션|다른 사람의 큐레이션|내가 작성한 단축어|다른 사람의 단축어|
|:---:|:---:|:---:|:---:|
|![IMG_5089](https://user-images.githubusercontent.com/91725382/204078079-6bebde16-2961-46bd-b773-3106abf53883.PNG)| ![IMG_5088](https://user-images.githubusercontent.com/91725382/204078085-b8ab15d9-6bd4-4452-9f1f-e7e92acfc284.PNG)| ![IMG_5087](https://user-images.githubusercontent.com/91725382/204078088-a524b50a-6e86-4a5a-8edc-e93dd47f9355.PNG)| ![IMG_5086](https://user-images.githubusercontent.com/91725382/204078096-ffae7940-3134-4400-9ab1-44d37717c324.PNG)|

2022-11-26 08:06 UTC, JMM00 requested changes
큐레이션 편집도 필요합니다!!!

2022-11-26 08:24 UTC, otoolz commented
> 큐레이션 편집도 필요합니다!!!

ㅖ..? 레알 없던 기능인디;;

2022-11-26 08:25 UTC, JMM00 commented
> > 큐레이션 편집도 필요합니다!!!
> 
> ㅖ..? 레알 없던 기능인디;;

에...? 현재 출시버전에는 큐레이션 편집 기능 존재합니다..!

2022-11-26 08:41 UTC, otoolz commented
> > > 큐레이션 편집도 필요합니다!!!
> > 
> > 
> > ㅖ..? 레알 없던 기능인디;;
> 
> 에...? 현재 출시버전에는 큐레이션 편집 기능 존재합니다..!

아하 isWriting이 편집에 대한거였군여. 단축어뷰에서랑 달라서 잘못봤습니다.
역시 엘리는 천재군요!

편집 버튼 메뉴에 추가완료했습니당

![IMG_97B5DC1EB47B-1](https://user-images.githubusercontent.com/91725382/204080277-39d16e04-fdd8-4e33-b423-c78ae7492e2d.jpeg)

2022-11-26 08:51 UTC, JMM00 approved these changes

2022-11-26 11:45 UTC, merged