[Feat] 로그인 없이 둘러보기
DeveloperAcademy-POSTECH/MacC-Team-HappyAnding pull request #372
Opened 2023-01-07 16:05 UTC by HanGyeongjun

## 관련 이슈
- closes #371

## 구현/변경 사항
- 로그인 화면에 '로그인 없이 둘러보기' 버튼 추가
- 비로그인 상태에서 제거, 비활성화, Alert을 표시하는 기능들
    - ReadShoercutsView의 좋아요, 다운로드, 이전 버전 다운로드 버튼 클릭 시 로그인 필요 Alert 추가
    - ReadShoercutsView의 답글 버튼 제거, 댓글 달기 워딩 변경 및 비활성화
    - 추천모음집 탭의 사용자를 위한 추천 모음집 항목 제거
    - 프로필 탭의 닉네임을 '사용자' 로 변경 및 닉네임 수정 버튼 제거
    - 프로필 탭의 단축어 작성, 추천 모음집 작성 버튼 클릭 시 로그인 필요 Alert 추가
    - 프로필 탭 설정 화면의 로그아웃, 탈퇴하기 버튼 대신 로그인 버튼 표시
- Alert의 '로그인하기' 버튼 클릭 시 로그인 화면 표시

## 스크린샷
모두 로그인 없이 둘러보기 시 표시되는 화면입니다.
로그인 상태의 화면은 이전과 달라진 항목이 없습니다.
|로그인 화면|로그인 Alert|프로필 화면|설정 화면|댓글 화면|
|:---:|:---:|:---:|:---:|:---:|
|![Simulator Screen Shot - iPhone 14 Pro - 2023-01-08 at 00 58 38](https://user-images.githubusercontent.com/94854258/211159622-bd025a2d-97ba-46f0-985c-7c80e36352be.png)|![Simulator Screen Shot - iPhone 14 Pro - 2023-01-08 at 00 58 47](https://user-images.githubusercontent.com/94854258/211159629-cb88c6db-5b28-4d6f-bfe7-543a9cb1e54e.png)|![Simulator Screen Shot - iPhone 14 Pro - 2023-01-08 at 00 59 02](https://user-images.githubusercontent.com/94854258/211159646-8ad47fad-8a5b-4f23-9002-a4f4e5166cce.png)|![Simulator Screen Shot - iPhone 14 Pro - 2023-01-08 at 00 59 08](https://user-images.githubusercontent.com/94854258/211159652-7ae2e151-0c04-49fd-91d1-126196044f8b.png)|![Simulator Screen Shot - iPhone 14 Pro - 2023-01-08 at 01 01 43](https://user-images.githubusercontent.com/94854258/211159670-182509cf-7346-4227-82fc-9da143459226.png)|

## 구현 방법
```Swift
@AppStorage("useWithoutSignIn") var useWithoutSignIn: Bool
```
AppStorage에 'useWithoutSignIn' 값을 추가해 로그인 없이 앱을 사용하는 상황을 관리했습니다.
기본값은 `false`로 설정되어 있고 
로그인 화면에서 '로그인 없이 둘러보기' 버튼을 눌렀을 때 `true`로 변경되고 앱을 둘러볼 수 있습니다.
alert 또는 설정 화면에서 '로그인하기' 버튼을 눌렀을 때 다시 `false`로 변경되고 로그인 화면을 표시합니다.
비로그인 상태에서 제한되는 기능이 있는 View에서 해당 AppStorage를 이용해 기능을 제한했습니다.

## 코드리뷰 시 참고해주세요

### Alert
- 현재 같은 Alert이 여러 곳에서 사용되고 있어서 하나로 관리하는 것이 필요해 보입니다.
- 익스텐션을 만들어 Alert을 사용하는 방법이 생각나는데, 이 방법이 좋을지 혹은 더 좋은 방법이 있는지 궁금합니다!
- Alert의 경우 추후 커스텀하자는 이야기도 나왔던 것으로 기억해서 지금 위의 방식대로 개선해놓을지, 커스텀 할 때 한 번에 변경할지도 의견 주시면 줗을 것 같습니다.

### 로그인 화면 Modal
- 현재 ReadShortcutView에서 뜨는 Alert의 '로그인하기' 를 클릭하고 로그인을 진행하면 원래 있던 단축어 상세 페이지가 아닌 탭의 최상단으로 이동합니다.
- 이 부분을 그대로 유지할지, 해당 상황에서 로그인 시 원래 페이지로 돌아오게 할지 논의가 필요합니다.
- 최선의 방법은 해당 View에 로그인 기능만 Modal로 띄워서 구현하는 것이라고 생각하는데, 이 방법으로 구현하기 위해서는 로그인 담당하셨던 분의 도움이 필요할 것 같습니다...

### 디자인과 워딩
- 로그인 화면의 '로그인 없이 둘러보기' 버튼의 폰트, 색상, 패딩은 현재 확정된 디자인이 아닙니다. 디자인 확정 시 변경될 수 있습니다.
- 로그인 없이 둘러보기 상태일 때 나타나는 새로운 워딩들이 있습니다. 테스트 시 함께 검토해 주세요.
    - 로그인 없이 둘러보기
    - 로그인 후 댓글을 작성할 수 있어요
    - 로그인을 진행해주세요
    - 이 기능은 로그인 후 사용할 수 있어요

### 기능 제거 / 비활성화 / Alert 기준
- 사용자가 로그인 없이 둘러보기 상황에서도 App의 기능을 파악할 수 있는가? 를 기준으로 했습니다.
- 변경할 부분 있으면 의견 남겨 주세요!
- **제거한 기능**: 버튼이 보이지 않아도 해당 기능이 있다는 것을 파악할 수 있는 것 / 컨텐츠를 표시할 수 없는 것
    - 답글 달기
    - 사용자 맞춤 추천 모음집
    - 닉네임 변경
- **비활성화한 기능**: 버튼이 보여야 기능을 알 수 있지만 label로 사용자에게 설명할 수 있는 것
    - 댓글 달기 textField
- **Alert을 띄우는 기능**: 버튼이 보여야 기능을 알 수 있는 것
    - 단축어 작성
    - 추천 모음집 작성
    - 단축어 다운로드 (이전 버전 다운로드)
    - 단축어 좋아요

2023-01-13 08:03 UTC, JIWON1923 requested changes
Components/ShortcutsCell
line 59에도 다운로드 막는 기능이 추가되어야합니다!

고생하셨어요 로겐 LGTM!

2023-01-13 08:03 UTC, JIWON1923 commented
## 피드백

### Alert
- 같은 Alert이라는건 로겐이 이번에 만든 "로그인을 진행해주세요" 관련 Alert이라면 하나로 관리할 필요가 있을 것 같고, 커스텀에 대한 구체적인 계획이 없기 때문에 지금 작업해주시면 감사하겠습니다 ^_^
- 제가 생각했을 땐 Alert는 deprecated 되어서 View를 확장해서 viewBuilder를 사용하는 방법이 적절할 것 같아요! 
  - 그런데 예상되는 이슈는 extension에서 저장속성을 선언할 수 없기 때문에 버튼에서의 액션을 어떻게 구동시킬지에 대한 고민이 더 필요할 것 같아요. 
  - 혹시 로겐이 extension으로 구현하는 방법을 알고 계신다면 그대로 작업하시면 될 듯 합니다

### 로그인 화면 Modal
- 로그인을 요청하는 타 어플리케이션의 경우, Alert를 띄우지 않고 바로 Modal로 이동하더라고요! 저도 그게 더 자연스러울 것 같긴 합니다!
- 제가 담당자인데 어떤 도움이 필요한지 말씀해주세요!

### 디자인과 워딩
- 메시지에서 특정 기능의 이름을 언급하지 않아도 좋을 것 같아요
  - "이 기능"이라고 통일하거나 또는 "로그인 후 더 다양한 숏컷집을 경험해보세요" 등의 다른 워딩을 사용하는건 어떨까요? 
  - 특정 부분만 상세 기능이 명시되어있고, 다른 부분은 "이 부분"이라고 통일 된 게 어색해보여서요!

2023-01-15 06:24 UTC, HanGyeongjun commented
> Components/ShortcutsCell line 59에도 다운로드 막는 기능이 추가되어야합니다!
> 
> 고생하셨어요 로겐 LGTM!

해당 버튼의 기능을 막지 않았었군요! 꼼꼼한 확인 감사합니다 👍🏻

2023-01-15 06:25 UTC, HanGyeongjun commented on HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
> +                            tryActionWithoutSignIn = true
ShortcutsCell의 다운로드 버튼에 로그인 없이 둘러보기 시 로그인 Alert을 띄우는 코드를 추가했습니다

2023-01-15 06:48 UTC, JIWON1923 approved these changes
고생했어요 로겐! Alert 재사용 방법은 같이 고민해봅시다!👍👍

2023-01-17 08:39 UTC, JMM00 approved these changes
로그인 정보가 없을 경우 처리되어야하는 자잘한 기능들을 잘 찾아서 구현해주셨네요~ 굳굳👍

2023-01-19 09:53 UTC, jim4020key approved these changes
꼼꼼하고 빠르게 잘 해주셨네요 !!!!👏 확인했습니다 ~! 설정화면에서 로그인이 바로 가능하다면 더 좋긴 할 것 같아요. 👍

2023-01-19 18:54 UTC, HanGyeongjun commented
5차 스프린트에서는 현재 구현된 대로 머지 후 출시 진행하겠습니다!
- Alert 코드 통합
- 모달을 통한 로그인
등 리팩토링은 6차 스프린트 또는 이후에 진행할 예정입니다.

2023-01-19 18:55 UTC, merged