[Feat] TextLiteral 작업
DeveloperAcademy-POSTECH/MacC-Team-HappyAnding pull request #385
Opened 2023-02-05 05:29 UTC by jim4020key

## 관련 이슈
- closes #199 

## 구현/변경 사항
- 텍스트들을 한 파일에 모아 수정 및 관리가 편리하도록 하는 작업입니다.
- Writing Convention에 맞춰 워딩 변경했습니다.
- 오타나 변수명 확인 부탁드립니다 ~!

2023-02-05 07:34 UTC, JIWON1923 approved these changes
꼼꼼하게 너무 잘 작업해주셨군요!!!👍

내부 열겨형과 타입 별칭을 활용해서 조금 더 간결하고 직관적으로 나타낼 수 있을 것 같아요
저는 단순히 코드 가독성과 범위 제한 측면에서 생각한것이기 때문에 제가 고려하지 못한 부분이 있다면 말씀해주세요!

+) 코드 컨벤션에서 변수의 타입 추론이 가능할 때, 타입을 명시할지 말지 결정해야할 것 같네요! (저희 컨벤션에 따로 언급되어있지 않아요)

2023-02-05 07:34 UTC, JIWON1923 commented on HappyAnding/HappyAnding/TextLiteral.swift
> +    static let nicknameTextFieldDuplicateCheck: String = "중복확인"
이런식으로 내부열거형을 통해 뷰 이름을 명시하는 방법은 어떨까요?
실 사용시 typealias를 통해 축약할 수도 있어서 직관적이고 간결하게 표현할 수 있을 것 같아요!
다른 프로젝트 보니 그린이 해주신 방법대로 한 번에 관리하고 있기는 하더라고요! 그런데 변수명에 뷰이름이 들어가면서 너무 길어지는 것 같아서 다른 의견 한 번 제시해봤슴당

``` swift
enum TextLiteral {
 /* 코드 생략  */
   enum NicknameTextField {
          static let length: String = "최대 8자까지 입력할 수 있어요"
          static let emoticon: String = "사용할 수 없는 문자가 포함되어 있어요"
          static let space: String = "공백 없이 한글 ,숫자, 영문만 입력할 수 있어요"
          static let duplicateTitle: String = "닉네임 중복 확인"
          static let duplicateSuccessMessage: String = "사용할 수 있는 닉네임이에요"
          static let duplicateFailMessage: String = "이미 사용 중인 닉네임이에요"
          static let duplicateSuccessLabel: String = "확인"
          static let duplicateFailLabel: String = "다시 입력하기"
          static let title: String = "닉네임 (최대 8글자)"
          static let duplicateCheck: String = "중복확인"
      }
 /* 코드 생략  */
}
```

``` swift
 typealias text = TextLiteral.NicknameTextField // 더 직관적인.. 어떤 변수명을 쓴다면.,.?
 /* 코드 생략  */
 Text(text.title)
```

2023-02-05 15:34 UTC, JIWON1923 commented on HappyAnding/HappyAnding/TextLiteral.swift
> +    static let nicknameTextFieldDuplicateCheck: String = "중복확인"
자료를 조금 더 찾아봤는데 Namespace를 내부 열거형으로 관리하는 사례가 없네요 ..
다시 생각해보니 가독성도 비슷할 것 같고, 제가 생각한 범위제한과 내부 열거형은 거리가 먼 것 같다는 생각이 들었어요

저는 그린이 지금 작업해주신 그대로 가져가면 될 것 같습니다!!!!!!

2023-02-06 07:16 UTC, mxnxxii approved these changes
링그 이즈 뭔들 ~ !! 좋아용

2023-02-06 10:33 UTC, jim4020key commented
> 꼼꼼하게 너무 잘 작업해주셨군요!!!👍
> 
> 내부 열겨형과 타입 별칭을 활용해서 조금 더 간결하고 직관적으로 나타낼 수 있을 것 같아요 저는 단순히 코드 가독성과 범위 제한 측면에서 생각한것이기 때문에 제가 고려하지 못한 부분이 있다면 말씀해주세요!
> 
> +) 코드 컨벤션에서 변수의 타입 추론이 가능할 때, 타입을 명시할지 말지 결정해야할 것 같네요! (저희 컨벤션에 따로 언급되어있지 않아요)

좋은 의견이라고 생각해요!! 중첩으로 표현하면 TextLiteral 파일 자체의 가독성이 높아질 것 같아요. 다만 저는 뷰 이름과 동일한 변수명을 사용하는게 좀 어색하다고 느꼈습니다.

타입 명시의 경우는 제가 다른 뷰 작업할 때 Color 사용하면서도 생각했던 부분이라 다음 회의 때 같이 얘기해봐요 ~!~! 쏘이 짱

2023-02-06 15:30 UTC, JMM00 approved these changes
덕분에 하나의 파일에서 모든 문자열들을 관리할 수 있게되어 좋은 것 같습니다. 
다만 제가 이번에 파일을 정리하면서 파일의 쓰임을 좀 더 명확하게 하기 위해 이름을 바꾼 파일이 존재합니다.
특히 WriteShortcutTitleView -> WriteShortcutView 로 변경하였는데 해당 파일명이 들어간 변수명이 있어서 이 부분은 추후 어떻게 반영할지 한번 더 이야기해보면 좋을 것 같습니다~

2023-02-06 17:09 UTC, HanGyeongjun requested changes
수고하셨습니다! 추후 워딩 변경이 있거나 현지화가 필요할 때 텍스트를 관리하기 훨씬 편해지겠네요 👍🏻 
그린이 작성해주신 부분을 살펴보다가 제가 워딩변경 하면서 미처 고려하지 못한 부분들에 수정 코멘트를 달았는데, 그 부분 확인해주시면 좋을 것 같습니다.
그리고 머지하실 때 앱 타겟 버전이 1.0.0으로 되어있는지 확인 후에 머지 부탁드려요!

2023-02-06 17:09 UTC, HanGyeongjun commented on HappyAnding/HappyAnding/TextLiteral.swift
> +    static let writeShortcutTitleViewPost: String = "단축어 등록"
```suggestion
    static let writeShortcutTitleViewPost: String = "단축어 작성"
```
이 부분이 바뀐 워딩에 들어있지 않았는데, 프로필 화면에도 '내가 작성한 단축어' 라고 표시가 되어 있고 추천 모음집도 작성으로 워딩이 통일되어 있어 단축어 등록 -> 단축어 작성으로 워딩을 변경하는 건 어떨까요?

2023-02-06 17:09 UTC, HanGyeongjun commented on HappyAnding/HappyAnding/TextLiteral.swift
> +    static let readShortcutCommentViewDeletionMessage: String = "답글도 함께 삭제됩니다. 댓글을 삭제하시겠습니까?"
```suggestion
    static let readShortcutCommentViewDeletionMessage: String = "답글도 함께 삭제돼요. 댓글을 삭제하시겠어요?"
```
이것도 바뀐 워딩에 들어있는 부분은 아닌데, 단축어 및 추천 모음집 삭제와 비슷한 어투로 변경하는 게 좋을 것 같습니다!

2023-02-06 17:09 UTC, HanGyeongjun commented on HappyAnding/HappyAnding/TextLiteral.swift
> +    static let writeCurationSetViewNoShortcuts: String = "아직 선택할 수 있는 단축어가 없어요.\n단축어를 업로드하거나 좋아요를 눌러주세요:)"
```suggestion
    static let writeCurationSetViewNoShortcuts: String = "아직 선택할 수 있는 단축어가 없어요\n단축어를 업로드하거나 좋아요를 눌러주세요"
```

2023-02-07 04:42 UTC, jim4020key commented
> 수고하셨습니다! 추후 워딩 변경이 있거나 현지화가 필요할 때 텍스트를 관리하기 훨씬 편해지겠네요 👍🏻 그린이 작성해주신 부분을 살펴보다가 제가 워딩변경 하면서 미처 고려하지 못한 부분들에 수정 코멘트를 달았는데, 그 부분 확인해주시면 좋을 것 같습니다. 그리고 머지하실 때 앱 타겟 버전이 1.0.0으로 되어있는지 확인 후에 머지 부탁드려요!

꼼꼼한 확인 감사합니다👍 워딩 및 버전 수정해서 반영했습니다. 확인부탁드려요!

2023-02-07 04:45 UTC, jim4020key commented
> 덕분에 하나의 파일에서 모든 문자열들을 관리할 수 있게되어 좋은 것 같습니다. 다만 제가 이번에 파일을 정리하면서 파일의 쓰임을 좀 더 명확하게 하기 위해 이름을 바꾼 파일이 존재합니다. 특히 WriteShortcutTitleView -> WriteShortcutView 로 변경하였는데 해당 파일명이 들어간 변수명이 있어서 이 부분은 추후 어떻게 반영할지 한번 더 이야기해보면 좋을 것 같습니다~

바뀐 파일명과 변수명을 반영해 놓는게 좋을까요??

2023-02-07 07:10 UTC, HanGyeongjun approved these changes
수정사항 확인했습니다! 👍🏻

2023-02-08 11:56 UTC, merged