[Feat] Share Extension에 TextLiteral 적용 등의 리팩토링 및 수정
DeveloperAcademy-POSTECH/MacC-Team-HappyAnding pull request #394
Opened 2023-02-13 12:12 UTC by HanGyeongjun

## 관련 이슈
- closes #393

## 구현/변경 사항
- Share Extension에서 사용되는 View 및 ViewController에 textLiteral을 적용했습니다.
- Share Extension의 View 이름도 main App에 맞게 `ShareExtensionWriteShortcutView` 로 변경했습니다.
- `SignInWithAppeView`에 textLiteral을 적용하고, 버튼의 text를 label로 변경했습니다.
- '데코레이션/꾸미기' 를 '데코레이션' 으로 변경했습니다.
- 카테고리 설명 글에도 줄바꿈이 빨리 되는 에러가 발생해 linebreaking extension을 적용시켰습니다.
  - 지난번 회의 때 이 설명글을 지우기로 했었는지 확실하지 않아서 일단 유지했습니다! 변경사항이 있으면 다음 스프린트때 반영하면 좋을 것 같습니다~!

2023-02-13 13:35 UTC, JIWON1923 requested changes
속성은 소문자 카멜케이스 적용해주세요!
extension 부분은 생각도 못했는데, 감사합니다~!

2023-02-13 13:35 UTC, JIWON1923 commented on HappyAnding/HappyAnding/TextLiteral.swift
> +    static let SignInWithAppleViewUseWithoutSignIn: String = "로그인 없이 둘러보기"
```suggestion
    static let signInWithAppleViewTitle: String = "ShortcutsZip"
    static let signInWithAppleViewSubTitle: String = "편리한 단축어 공유 플랫폼"
    static let signInWithAppleViewSignInWithApple: String = "Apple로 로그인"
    static let signInWithAppleViewUseWithoutSignIn: String = "로그인 없이 둘러보기"
```

2023-02-13 13:35 UTC, JIWON1923 commented on HappyAnding/HappyAnding/TextLiteral.swift
> +    static let CustomShareViewControllerCheck: String = "확인"
```suggestion
    static let customShareViewControllerSignInAlertTitle: String = "로그인을 먼저 진행해주세요"
    static let customShareViewControllerSignInAlertMessage: String = "이 기능은 로그인 후 사용할 수 있는 기능이에요"
    static let customShareViewControllerLinkVaildAlertTitle: String = "잘못된 접근이에요"
    static let customShareViewControllerLinkVaildAlertMessage: String = "해당 링크는 ShortcutsZip으로 공유할 수 없어요"
    static let customShareViewControllerCheck: String = "확인"
```

2023-02-13 13:35 UTC, JIWON1923 commented on HappyAnding/HappyAnding/Views/SignInViews/SignInWithAppleView.swift
> +            Text(TextLiteral.SignInWithAppleViewTitle)
```suggestion
            Text(TextLiteral.signInWithAppleViewTitle)
```

2023-02-13 13:35 UTC, JIWON1923 commented on HappyAnding/HappyAnding/Views/SignInViews/SignInWithAppleView.swift
> +            Text(TextLiteral.SignInWithAppleViewSubTitle)
```suggestion
            Text(TextLiteral.signInWithAppleViewSubTitle)
```

2023-02-13 13:35 UTC, JIWON1923 commented on HappyAnding/HappyAnding/Views/SignInViews/SignInWithAppleView.swift
> +                    Label(TextLiteral.SignInWithAppleViewSignInWithApple, systemImage: "applelogo")
```suggestion
                    Label(TextLiteral.signInWithAppleViewSignInWithApple, systemImage: "applelogo")
```

2023-02-13 13:35 UTC, JIWON1923 commented on HappyAnding/HappyAnding/Views/SignInViews/SignInWithAppleView.swift
> +                Text(TextLiteral.SignInWithAppleViewUseWithoutSignIn)
```suggestion
                Text(TextLiteral.signInWithAppleViewUseWithoutSignIn)
```

2023-02-13 13:35 UTC, JIWON1923 commented on HappyAnding/ShareExtension/CustomShareViewController.swift
> +            let action = UIAlertAction(title: TextLiteral.CustomShareViewControllerCheck, style: .default) { _ in
```suggestion
            let alert = UIAlertController(title: TextLiteral.customShareViewControllerSignInAlertTitle, message:
                                            TextLiteral.customShareViewControllerSignInAlertMessage, preferredStyle: .alert)
            let action = UIAlertAction(title: TextLiteral.customShareViewControllerCheck, style: .default) { _ in
```

2023-02-13 13:35 UTC, JIWON1923 commented on HappyAnding/ShareExtension/CustomShareViewController.swift
> +                let action = UIAlertAction(title: TextLiteral.CustomShareViewControllerCheck, style: .default) { action in
```suggestion
                let alert = UIAlertController(title: TextLiteral.customShareViewControllerLinkVaildAlertTitle, message: TextLiteral.CustomShareViewControllerLinkVaildAlertMessage, preferredStyle: .alert)
                let action = UIAlertAction(title: TextLiteral.customShareViewControllerCheck, style: .default) { action in
```

2023-02-13 13:50 UTC, HanGyeongjun commented
> 속성은 소문자 카멜케이스 적용해주세요! extension 부분은 생각도 못했는데, 감사합니다~!

제가 UpperCamelCase로 작성했었군요! 빨리 SwiftLint를 적용해야겠네요...

2023-02-13 15:00 UTC, HanGyeongjun commented on HappyAnding/ShareExtension/ShareExtensionWriteShortcutView.swift
> +                                               placeholder: TextLiteral.writeShortcutTitleViewNamePlaceholder,
반영할게요! 👍🏻

2023-02-14 02:09 UTC, JIWON1923 approved these changes

2023-02-14 03:10 UTC, merged