[Feat] 유저 단축어 등급 기능 추가
DeveloperAcademy-POSTECH/MacC-Team-HappyAnding pull request #412
Opened 2023-02-28 14:52 UTC by JMM00

## 관련 이슈
- closes #396

## 구현/변경 사항
- 등급 뱃지 이미지 크기별 추가
- 단축어 글 일정 갯수 이상 작성 시 각 등급 뱃지로 프로필 이미지 대체
- 등급 상승 시 등급 상승 알림창 띄우기
- 단축어 삭제 시 등급 하락 경고 문구 추가 (실제 하락하는 경우에만)

## 스크린샷

### iPhone SE

https://user-images.githubusercontent.com/41153398/221887894-13ad3d72-478c-422b-aee9-14c74240f0de.mp4

### iPhone14 pro

https://user-images.githubusercontent.com/41153398/221887910-381f338d-3388-4a63-8523-137356d5d2c5.mp4

| iPhone SE | iPhone14 pro
|--|--|
| ![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-02-28 at 23 34 50](https://user-images.githubusercontent.com/41153398/221888253-b9cdab84-644c-4529-adfe-7b4996ff7843.png) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-02-28 at 23 28 06](https://user-images.githubusercontent.com/41153398/221888243-14f59b2d-8ad5-4d9e-9ceb-789297dfabac.png) |

## To Reviewer
- 등급 상승 알림창은 특수한 경우 + 다시 볼 수 있는 방법이 존재하지 않아 배경 클릭 시 창이 닫히는 기능을 추가하지 않았습니다. 다만 애니메이션이 재생되는 동안 닫지 못하는 것이 답답함을 유발할 수도 있음을 고려해 애니메이션 속도를 조금 빠르게 조정했습니다.
- 등급 상승 알림창은 기본 알림창처럼 동작하는 것이 아닌 상단뷰의 ZStack에서 조건을 검사해서 띄워주는 방식으로 나타날 때 갑자기 등장해 어색하다고 느껴질 수 있습니다. 이부분을 수정하기 위해서 조건에 해당하는 값을 변경하는 부분에 애니메이션을 넣었지만 효과가 없었습니다ㅠㅠ 혹시 다른 방법을 아신다면 피드백 부탁드립니다!

2023-03-01 05:10 UTC, HanGyeongjun requested changes
데이터 구조나 함수 되게 깔끔하게 구현해 주신 것 같아요! 수고하셨습니다 👍🏻 
아래 피드백만 검토 부탁드립니다.

- alert을 제외한 다른 아이콘 해상도가 너무 낮게 설정되어 있는 것 같아요. 작은 아이콘인데도 낮은 해상도로 보여서 해상도를 높인 에셋으로 재등록해주셨으면 좋겠습니다!
- 라이트모드일 때는 괜찮은데, 다크모드에서 실행했을 경우 Alert창의 텍스트 및 xmark가 흰색인 Alert배경과 너무 대비가 약해 사용자가 불편해 할 것으로 예상됩니다. 두 가지 해결방향이 생각나는데 어떤 방향이 더 좋을까요?
    1. Alert배경은 다크모드에서도 흰색으로 유지하고 텍스트 및 xmark 색상을 진하게 변경하자.
    2. 텍스트 및 xmark 색상은 현행대로 gray5로 유지하고 Alert배경색을 background 회색보다 밝은 회색으로 설정하자.
    
![IMG_7110](https://user-images.githubusercontent.com/94854258/222050490-999ad41b-2242-4209-a62f-38ab4dddd318.png)

2023-03-01 07:26 UTC, JIWON1923 commented
혹시 지민님이 원하시는 뷰 전환 효과가 이게 맞을까요?

https://user-images.githubusercontent.com/68676844/222071752-41db5222-fbec-4773-8ed1-7e0a83cd1a04.mov

2023-03-01 08:20 UTC, JIWON1923 approved these changes
정말 어려운 태스크였을텐데 너무 깔끔하게 잘 해주셨네요!
현재 레벨 1에서 나타나는 이슈가 있습니다. 제안드린 코드 반영해주세요~
고생하셨어요~!

2023-03-01 08:20 UTC, JIWON1923 commented on HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
> +        }
count 변수에 대한 조건문이니까 if - else if - else보다 switch 문으로 표현하는건 어떨까요?
리턴형이 있으니 멤버를 생략하는게 더 좋아보이네요

```suggestion
        switch count {
        case ..<1:
            return .level0
        case 1..<5:
            return .level1
        case 5..<10:
            return .level5
        case 10..<25:
            return .level10
        case 25..<50:
            return .level25
        default:
            return .level50
        }
```

2023-03-01 08:20 UTC, JIWON1923 commented on HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
> +        }
### 제안
`shortcutsMadeByUser.count`가 1, 5, 10, 25, 50 이라면 true, 아니라면 false를 리턴하는 코드입니다.
🍯팁: 단일 표현식 함수이므로 리턴형을 생략할 수 있어요!

```suggestion
        [1, 5, 10, 25, 50].contains(shortcutsMadeByUser.count)
```

### 0에서 1로 바꾼 이유
기존 코드에서 마지막 단축어를 삭제할 때, 경고 문구가 뜨지 않아요!
현재 단축어 개수가 1일 때 강등이기 때문!

https://user-images.githubusercontent.com/68676844/222079407-a4fcd1a1-0955-4b86-9aca-5249755bb574.mov

2023-03-01 08:20 UTC, JIWON1923 commented on HappyAnding/HappyAnding/Views/Components/GradeAlertView.swift
> +                        if index - 1 < 0 {
```suggestion
                        if index < 1 {
```

2023-03-01 08:20 UTC, JIWON1923 commented on HappyAnding/HappyAnding/Views/Components/GradeAlertView.swift
> +                                .frame(height: 198)
```suggestion
                                .frame(width: 170, height: 198)
```

## 이슈
현재 레벨 1로 상승할 때 다음과 같은 이슈가 있어요 (양 옆 하얀색 상자가 나타납니다)


https://user-images.githubusercontent.com/68676844/222082316-a5b0667a-10e2-4632-ba84-6ed41be8a429.mov

2023-03-01 08:22 UTC, HanGyeongjun commented
> 정말 어려운 태스크였을텐데 너무 깔끔하게 잘 해주셨네요! 현재 레벨 1에서 나타나는 이슈가 있습니다. 제안드린 코드 반영해주세요~ 고생하셨어요~!

와우... 엄청난 코드리뷰네요 👍🏻

2023-03-01 11:12 UTC, JMM00 commented on HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
> +        }
오우...이런 실수를.. 표현식도 훨씬 간단한 방법이 있군요..! 오늘도 배워갑니다 개발천재 쵝오쵝오

2023-03-01 11:17 UTC, JMM00 commented on HappyAnding/HappyAnding/Views/Components/GradeAlertView.swift
> +                Text(isTextShowing ? "단축어 작성 레벨이 상승했어요!" : "")
> 혹시 지민님이 원하시는 뷰 전환 효과가 이게 맞을까요?

헐 네...어디서 애니메이션을 주면 될까요?

2023-03-01 11:21 UTC, JMM00 commented
> 데이터 구조나 함수 되게 깔끔하게 구현해 주신 것 같아요! 수고하셨습니다 👍🏻 아래 피드백만 검토 부탁드립니다.
> 
> * alert을 제외한 다른 아이콘 해상도가 너무 낮게 설정되어 있는 것 같아요. 작은 아이콘인데도 낮은 해상도로 보여서 해상도를 높인 에셋으로 재등록해주셨으면 좋겠습니다!
>   
>   * Figma에서 export하실 때 1x말고 3x설정으로 뽑아주시면 해결될 것 같습니당
> * 라이트모드일 때는 괜찮은데, 다크모드에서 실행했을 경우 Alert창의 텍스트 및 xmark가 흰색인 Alert배경과 너무 대비가 약해 사용자가 불편해 할 것으로 예상됩니다. 두 가지 해결방향이 생각나는데 어떤 방향이 더 좋을까요? 개인적으로는 다크모드에서 갑자기 큰 흰색 창이 나타나면 불편하게 느낄 수 있을 것 같아 두 번째 해결방법이 좋을 것 같습니다
>   
>   1. Alert배경은 다크모드에서도 흰색으로 유지하고 텍스트 및 xmark 색상을 진하게 변경하자.
>   2. 텍스트 및 xmark 색상은 현행대로 gray5로 유지하고 Alert배경색을 background회색으로 설정하자. -> 배경색과 같지만 배경이 Dimmed 되어있어서 두 색상 간의 차이를 인식할 수 있을 거라고 생각합니다! 잘 인지가 안 된다면 더 밝은 회색으로 설정하는 방향도 좋습니다.
> 
> Dark	Light
> ![IMG_7110](https://user-images.githubusercontent.com/94854258/222050490-999ad41b-2242-4209-a62f-38ab4dddd318.png)	![image](https://user-images.githubusercontent.com/94854258/222050817-acf7767b-d152-43fa-86ea-f1c3fd1aa981.png)

꼼꼼한 리뷰 감사합니다! 
1. 해상도 부분은 이미지 다시 추가했습니다!
2. alert의 경우 배경색을 기존 배경색과 동일한 shortcutsZipWhite로 설정한 경우
<img src = "https://user-images.githubusercontent.com/41153398/222125014-e1e3ceb7-aab7-4a92-ae71-8fb2cacd0013.png" width=300>
이런 모습인데 배경과 차이가 느껴지는 정도라고 생각되는데 어떻게 생각하시나요?

2번 괜찮다고 생각되시면 바로 수정 푸시하겠습니다!

2023-03-01 11:26 UTC, HanGyeongjun commented
@JMM00 변경된 색상 구분 잘 되어서 괜찮을 것 같습니다!

2023-03-01 11:29 UTC, JMM00 commented
> 혹시 지민님이 원하시는 뷰 전환 효과가 이게 맞을까요?

네!!!!! 맞아요!!!!! 어디서 해당 애니메이션을 넣어야하죠,,,.????ㅠㅠㅠㅠㅠ

2023-03-01 11:30 UTC, JMM00 commented on HappyAnding/HappyAnding/Views/Components/GradeAlertView.swift
> +                Text(isTextShowing ? "단축어 작성 레벨이 상승했어요!" : "")
반영했습니다!! 굿굿

2023-03-01 11:32 UTC, JMM00 commented
> 정말 어려운 태스크였을텐데 너무 깔끔하게 잘 해주셨네요! 현재 레벨 1에서 나타나는 이슈가 있습니다. 제안드린 코드 반영해주세요~ 고생하셨어요~!

꼼꼼한 리뷰 감사합니다~!!!!!!! 제가 놓친 부분들까지 꼼꼼하게 잡아주셨네요ㅠㅠ 제가 마음만 급해서..부족한 pr을 올린 것 같아 죄송합니다. 앞으로는 좀 더 꼼꼼하게 확인 후 진행하겠습니다!! 감사합니다

2023-03-01 11:33 UTC, HanGyeongjun approved these changes
에셋 변경 및 TextLiteral 반영도 확인했습니다!

2023-03-01 12:57 UTC, JIWON1923 approved these changes

2023-03-01 12:57 UTC, JIWON1923 commented on HappyAnding/HappyAnding/Views/ShortcutsZipView.swift
> +            }
@JMM00 
withAnimation 내부에서 상태를 변경하면 사용하면 됩니다!
그런데 이렇게 사용하면 원래는 뷰가 사라질 때에도 자연스럽게 사라져야하는데, 왜 적용이 안 되는지는 저도 더 분석해봐야할 것 같아요

```suggestion
            .onChange(of: gradeAlerter.isPresented) { newValue in
                withAnimation {
                    isGradeAlertShowing = newValue
                }
            }
```

2023-03-01 13:19 UTC, JIWON1923 commented
푸시 이후에는 리베이스 말고 머지로 최신 디벨롭 반영하는게 좋다고 하네요
디벨롭을 건드리지 않는다는점에서 좋기는 하지만, 중복된 커밋이 너무 많이 남네요!ㅠ
[관련 자료](https://djkeh.github.io/articles/Do-not-rebase-commits-that-you-have-pushed-to-a-public-repository-kor/)

2023-03-02 01:45 UTC, JMM00 commented on HappyAnding/HappyAnding/Views/ShortcutsZipView.swift
> +            }
저도 이상하게 onChange에서는 뷰가 사라질때 값 변경은 감지를 못해서 Binding변수로 따로 처리해줬습니다. 이것과 연관이 있을 수도 있겠군요ㅠㅠ

2023-03-02 06:40 UTC, merged