[Feat] IconModalView 심볼 추가
DeveloperAcademy-POSTECH/MacC-Team-HappyAnding pull request #433
Opened 2023-03-29 22:00 UTC by jim4020key

## 관련 이슈
- closes #408 

## 구현/변경 사항
- 단축어 기본앱에 포함된 심볼들을 추가하였습니다.
- 3/1 회의 결과를 반영하여 검색을 추가하기 전 모든 심볼들이 한 화면에 나타나도록 하고, 카테고리를 선택함으로써 해당 카테고리로 이동할 수 있도록 합니다.
- 카테고리는 section header로 고정되어 아래로 스크롤시에도 항상 볼 수 있습니다.
- 카테고리는 기본앱과 같이 화면을 열 때마다 랜덤으로 배열됩니다.
- padding이나 글자 색 등 변경이 필요한 부분 있으면 말씀해주세요 !!
- 현재 딕셔너리 [String: [String]]로 표현되어 있는 symbols를 어떻게 관리하는 것이 효율적일까요 ... 🤯

## 스크린샷
|iPhone SE|iPhone 14|iPhone 14 Pro Max|
|:---:|:---:|:---:|
|![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-03-30 at 06 46 18](https://user-images.githubusercontent.com/76623853/228675159-2b2518da-4cfd-4504-be75-aec628888f87.png)|![Simulator Screen Shot - iPhone 14 - 2023-03-30 at 06 45 03](https://user-images.githubusercontent.com/76623853/228675190-3ea4f5dd-0174-4d87-8912-3cfaf87641fd.png)|![Simulator Screen Shot - iPhone 14 Pro Max - 2023-03-30 at 06 47 15](https://user-images.githubusercontent.com/76623853/228675218-673963c5-e3df-4eb3-9c61-0373a2ee3c9c.png)|

## 추가
- 테스트하면서 심볼을 선택하면 맨 위 미리보기로 바로 이동하는 기능이 있으면 좋겠다고 생각해서 추가해보려고 하는데 어떨까요?

2023-04-07 09:04 UTC, JIWON1923 approved these changes

2023-04-07 10:17 UTC, JIWON1923 commented
<img src = "https://user-images.githubusercontent.com/68676844/230591775-15e04281-2a57-45d4-9662-2f8f852d79f8.png" width = 250> 
이 부분 아이콘이 너무 작아보이지 않나유?

2023-04-07 10:23 UTC, JIWON1923 commented
자료 저장 방식은... 더 생각해봐야겠는걸요..?
API들 찾아보면서 비슷한 사례 찾아보고, 적용시켜야할 것 같아요🧠

그린 너무 고생많으셨습니다 👍

2023-04-08 14:30 UTC, HanGyeongjun commented
> <img alt="" width="250" src="https://user-images.githubusercontent.com/68676844/230591775-15e04281-2a57-45d4-9662-2f8f852d79f8.png">
> 
> 이 부분 아이콘이 너무 작아보이지 않나유?

이 부분은 제가 SF Symbols 통일시키면서 변경한 부분인데, 여기에만 예외적으로 좀 더 큰 크기의 SF Symbols를 적용시키는 게 더 자연스러울까요?
저도 이 부분 작업하면서 인지했지만 따로 대안이 없어서 이대로 했었는데, 좀 어색해 보이긴 해서 바꾸는 게 필요해 보이긴 합니다.

2023-04-09 11:33 UTC, HanGyeongjun requested changes
수고하셨습니다! 아이콘들 많아지니 좋네요... 아래 사항들 한 번 확인해주시면 감사하겠습니당. 
아니면 디자인 부분은 제가 해당 브렌치에서 바로 수정해도 괜찮을 거 같아요! 오케이 해 주시면 한 번 디자인 수정 해 보겠습니다.

- 카테고리 섹션 HStack 버튼 관련
    - 카테고리 섹션 HStack ScrollBar를 hidden 해 주시면 좋을 것 같습니다
    - 뒷부분 컬러 추가해서 스크롤 시 아이콘들 안 보이게 되면 좋을 것 같아요
    - 각각의 버튼을 터치했을 때 스크롤 애니메이션과 함께 내려가면 좋을 것 같아요
    -  버튼 터치하고 해당 부분으로 이동할 때 약간씩 다른 위치로 이동해서 조금 어색한 것 같아요. 같은 위치로 되게 하는 거 구현이 까다로울까요..?
    - 섹션 버튼 스타일을 border만 있는 형태로 바꾸는 것은 어떨까요..? 그냥 개인적인 의견입니당
- ‘기호’ 랑 카테고리 설명하는 텍스트 사이즈가 같아서 사용자가 혼란을 얻을 수 있을 것 같은데 더 좋은 방법은 고민이 필요해보이네요...
- 혹시 사용자가 스크롤하면 위쪽 카테고리 섹션도 맞춰서 스크롤되고 자동으로 선택되는 기능이 가능할까요..? 스크롤리더 쓰면 되긴 될 것 같은데 랜덤으로 순서가 배치되면 좀 어렵겠군요...
- 선택하면 위로 올라가는 것보다 위쪽에 작게 프리뷰를 띄워주는게 UX적으로 좋지 않을까요?
    - 고민중일 떄 여러 번 선택하는 경우가 있을 것 같은데 그때마다 매번 위로 올라가면 불편할 것 같아요.
    - 내려갈때 조금씩 작아지면서 위쪽에 고정되게 할…수 있나요..? ㅎㅎㅎ
- 데이터 관리는 고민되네요... 아니면 그냥 model로 분리해도 되지 않을까 하는 생각이 들긴 합니당

2023-04-21 05:37 UTC, mxnxxii commented
카테고리 버튼 리스트에서 선택되어있을 때, 다른 버튼들이 선택불가능 한 것 처럼 느껴지는 것 같아요 !!

2023-04-21 05:38 UTC, mxnxxii commented
카테고리 버튼 리스트에서 선택되어있을 때, 다른 버튼들이 선택불가능 한 것 처럼 느껴지는 것 같아요 !!

2023-05-05 15:22 UTC, jim4020key commented
> 수고하셨습니다! 아이콘들 많아지니 좋네요... 아래 사항들 한 번 확인해주시면 감사하겠습니당. 아니면 디자인 부분은 제가 해당 브렌치에서 바로 수정해도 괜찮을 거 같아요! 오케이 해 주시면 한 번 디자인 수정 해 보겠습니다.
> 
> * 카테고리 섹션 HStack 버튼 관련
>   
>   * 카테고리 섹션 HStack ScrollBar를 hidden 해 주시면 좋을 것 같습니다
>   * 뒷부분 컬러 추가해서 스크롤 시 아이콘들 안 보이게 되면 좋을 것 같아요
>   * 각각의 버튼을 터치했을 때 스크롤 애니메이션과 함께 내려가면 좋을 것 같아요
>   * 버튼 터치하고 해당 부분으로 이동할 때 약간씩 다른 위치로 이동해서 조금 어색한 것 같아요. 같은 위치로 되게 하는 거 구현이 까다로울까요..?
>   * 섹션 버튼 스타일을 border만 있는 형태로 바꾸는 것은 어떨까요..? 그냥 개인적인 의견입니당
>   * HStack을 양쪽 끝까지 늘려도 그렇게 어색하진 않을 것 같아요. 오히려 지금 양쪽 16픽셀 마진이 있어서 더 어색해보이는 것 같습니다
> * ‘기호’ 랑 카테고리 설명하는 텍스트 사이즈가 같아서 사용자가 혼란을 얻을 수 있을 것 같은데 더 좋은 방법은 고민이 필요해보이네요...
> * 혹시 사용자가 스크롤하면 위쪽 카테고리 섹션도 맞춰서 스크롤되고 자동으로 선택되는 기능이 가능할까요..? 스크롤리더 쓰면 되긴 될 것 같은데 랜덤으로 순서가 배치되면 좀 어렵겠군요...
> * 선택하면 위로 올라가는 것보다 위쪽에 작게 프리뷰를 띄워주는게 UX적으로 좋지 않을까요?
>   
>   * 고민중일 떄 여러 번 선택하는 경우가 있을 것 같은데 그때마다 매번 위로 올라가면 불편할 것 같아요.
>   * 내려갈때 조금씩 작아지면서 위쪽에 고정되게 할…수 있나요..? ㅎㅎㅎ
> * 데이터 관리는 고민되네요... 아니면 그냥 model로 분리해도 되지 않을까 하는 생각이 들긴 합니당

카테고리 버튼이 border만 있는 형태가 된다면 로미가 말한 부분이 해결될까요 ???
꼼꼼한 로겐 UX를 부탁해 ~ 👏

2023-05-08 02:30 UTC, HanGyeongjun commented
쏘이가 코드, 아이콘 크기 제안해주신 부분이랑 제 코드리뷰 같이 제가 이어서 작업하겠습니당

2023-05-26 19:35 UTC, HanGyeongjun approved these changes

2023-05-26 19:37 UTC, HanGyeongjun commented
카테고리 섹션 HStack 관련 디자인 개선 진행했습니다! 아래 사항은 따로 이슈 및 브랜치 생성해서 추후 스프린트에서 진행 예정입니다.
- 아이콘 프리뷰
- HStack 자동 선택 및 스크롤

2023-05-26 19:40 UTC, merged