[Feat] #468 read curatoin view model 적용
DeveloperAcademy-POSTECH/MacC-Team-HappyAnding pull request #469
Opened 2023-06-18 14:16 UTC by JIWON1923

## 관련 이슈
- closes #468

## 구현/변경 사항
- Read Curation View Model 생성했습니다.
- 특정 모델에 init 함수를 정의해서 조금 편하게 쓸 수 있도록 수정했습니다.
- viewModel의 의존성은 Navigation Stack에서 제공합니다
- 63370d5bbf2ae2afd2d30bad4755663048b0d6b3 의 경우, 그린이 작업해주신 부분인데 같이 수정해서 업로드합니다.

## 스크린샷
뷰 변경사항은 없습니다.

2023-06-21 21:02 UTC, jim4020key requested changes
🚨 탈퇴한사용자가 제대로 표시 되지 않는데 확인 부탁해요 ~~~~~ !!

<img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/76623853/058c1960-0cb5-42dd-a7ef-51d90c15f1ea" width="300">

2023-06-25 10:46 UTC, JIWON1923 commented
@jim4020key 꼼꼼한 리뷰 감사해요~!

2023-07-19 17:01 UTC, JMM00 approved these changes
덕분에 참고가 많이 되었습니다! 제가 확인한 부분에서는 문제없이 동작했습니다👍

2023-07-21 16:16 UTC, jim4020key approved these changes
탈퇴한 사용자 disable은 readshortcutviewmodel PR에서 처리하겠습니다 ~!
쏘이 짱 🫶

2023-07-22 05:50 UTC, merged